name: Convert CSV to JSON (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Download CSV and Convert to JSON
      run: |
        CSV_URL="https://trip.lareward.com/hotel.csv"
        CSV_FILE="hotel.csv"
        JSON_FILE="hotel.json"

        echo "Mulai mengunduh file CSV dari $CSV_URL..."
        curl -L $CSV_URL -o $CSV_FILE --progress-bar

        if [ ! -f "$CSV_FILE" ]; then
          echo "Error: File CSV gagal diunduh atau tidak ditemukan."
          exit 1
        fi
        echo "Unduh CSV selesai. Ukuran: $(du -sh $CSV_FILE | awk '{print $1}')"

        echo "Memulai konversi CSV ke JSON..."
        # --- PERHATIKAN INDENTASI DI BAWAH INI ---
        # Setiap baris kode Python (termasuk 'import pandas as pd')
        # harus diindentasi dengan 8 spasi dari awal baris (atau 2 spasi dari `python -c "`).
        python -c "
import pandas as pd
import json
import os

csv_file = '$CSV_FILE'
json_file = '$JSON_FILE'
chunksize = 25000 

with open(json_file, 'w', encoding='utf-8') as f:
    f.write('[\n')

first_chunk_record = True

for i, chunk in enumerate(pd.read_csv(csv_file, chunksize=chunksize, dtype=str)):
    print(f'  Memproses chunk {i+1} dengan {len(chunk)} baris...')
    
    records = chunk.where(pd.notna(chunk), None).to_dict(orient='records')
    
    with open(json_file, 'a', encoding='utf-8') as f:
        for j, record in enumerate(records):
            if not first_chunk_record:
                f.write(',\n')
            json.dump(record, f, ensure_ascii=False, indent=2)
            first_chunk_record = False

with open(json_file, 'a', encoding='utf-8') as f:
    f.write('\n]\n')

print('Konversi selesai!')
print(f'Ukuran file JSON yang dihasilkan: {os.path.getsize(json_file) / (1024 * 1024):.2f} MB')
"
        # --- AKHIR DARI BLOK PYTHON INLINE ---
        if [ ! -f "$JSON_FILE" ]; then
          echo "Error: File JSON tidak berhasil dibuat."
          exit 1
        fi

    - name: Konfigurasi Git LFS
      run: |
        git config lfs.url "https://github.com/${{ github.repository }}.git/info/lfs"
        git lfs install --local

    - name: Add dan Commit File JSON
      run: |
        git add ${{ github.workspace }}/hotel.json
        git commit -m "Update hotel.json from latest CSV" || echo "Tidak ada perubahan untuk di-commit"

    - name: Push Perubahan ke Repositori
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
